### ISSUE TITLE
Color not reset after PvP Tagged when using Nametagedit

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager-Issues#143]
**Describe the bug**
When you use [nametagedit](https://www.spigotmc.org/resources/nametagedit.3836/) with PvPManager, setting a color for a user above their head, when you PvP tag in PvPManager it sets their nametag to red, but when it runs out, it does not set it back to the color it was before from Nametagedit!

I made a bug report an entire year ago for this for the nametagedit plugin, but nobody even bothered to reply.
https://github.com/sgtcaze/NametagEdit/issues/490

**To Reproduce**
1. Setup nametagedit with a colored tag above head
2. Get PvP tagged so it turns red
3. Wait for the PvP tag to end

**Expected behavior**
To go back to the color that was set via nametagedit

**Plugin and Server version**
1.13.20
paper 1.12.2

**Comment by NoChanceSD** [comment]
PvPManager usually saves the current scoreboard team of the player, then sets the player to a team created by PvPManager to change the name and when combat ends it sets it back to whatever team it was on previously.
This allows compatibility with almost any plugin using the API, the problem is Nametagedit uses packets which is pretty much "fake teams", so afaik I have no way of setting the team back like it was unless I hook directly into Nametagedit.
I also sent a message to the author probably a year ago as well, asking if there was any better way to do this or if I was missing something but got no reply.  I guess I will just end up directly hooking into Nametagedit to handle this.

**Comment by TomLewis** [comment]
Ahh thanks for the technical reason, always good to understand.

I'm still using "Colored Tags" which hasn't been updated since 2016, it still works, but I really need to move off 1.12.2 lol

The NameTagEdit has a few more features too, it looks like it allows setting a nametag based off a command, so I could dynamically create custom nametags on the fly without having to edit a config, I didn't get that far in testing as I noticed the PvP issue and ditched it a year ago.

Unless there's a better nametag plugin out there worth testing that works 1.12.2-1.16.5

**Comment by NoChanceSD** [comment]
I know CMI allows changing the tab playerlist and stuff like that, I'm not sure if it changes nametags as well but if it does it should work fine with PvPManager teams. Other than that I think the "Tab" plugin is also a decent choice for nametags but it will likely have the same issue as Nametagedit.

Either way, I will work on adding support for Nametagedit in a future update, as well as support for Tab since they are used by so many servers currently.

**Comment by TomLewis** [comment]
Thanks man, I do use CMI but I've had to disable all their tab based stuff, as it breaks a lot of things.

NameTagEdit looks like the best shout at present! I briefly used TAB but it changes so much, I need a lot of time to customise it how I want! So supporting both would be fantastic! 

You might be able to gain features by adding hooks, like showing a PvP cooldown above someone's head instead of in the lower thrid above the hotbar.

**Comment by TomLewis** [comment]
Hey @ChanceSD Im finally upgrading from 1.12.2 to 1.17/1.18 and tried Tab out like you suggested, sadly this does the exact same thing, it just resets a players nametag to white and does not set it back again.

**Comment by ChanceSD** [comment]
> Hey @ChanceSD Im finally upgrading from 1.12.2 to 1.17/1.18 and tried Tab out like you suggested, sadly this does the exact same thing, it just resets a players nametag to white and does not set it back again.
> 
> Sadly CMI Dev never responded to my suggestion to add this as a feature, they only do tablist, which is annoying as I own CMI.

With TAB seems like they have an anti override setting, if left to true then PvPManager will only apply the glow without changing the prefix, which is pretty usable imo, unless you really want the combat tag prefix. 
If set to false then indeed it leaves the player's name white after PvPManager attempts to change it back to what it was.

I'm gonna look into a TAB hook though, I added a graph to bStats to see how many PvPManager users use TAB vs NametagEdit  and TAB wins by a lot.

**Comment by TomLewis** [comment]
Worth a hook to solve that issue so we have the option, I'm not sure how much my PvP players want a glow, but that was my "fix" that I came up with earlier too. Does make the glow arrows useless then.

**Comment by ChanceSD** [comment]
> Worth a hook to solve that issue so we have the option, I'm not sure how much my PvP players want a glow, but that was my "fix" that I came up with earlier too. Does make the glow arrows useless then.

If you can come on discord I have a dev build I can send you earlier if you want. Think I got it working well, otherwise it will be on Spigot eventually.

**Comment by ChanceSD** [comment]
Think this can be closed now

**Comment by TomLewis** [comment]
Thanks! Sorry only just going throguh all my Github notificaitons! 

For an update for anyone that stumbles across this post, since the initial post Im now using Purpur 1.18.1 with Tab and this is resolved and working!
