### ISSUE TITLE
Use MysqlPlayerDataBridge and go offline in combat

### ISSUE THREAD

**Issue by HoYa-DaiBo** [ChanceSD/PvPManager-Issues#144]
When using MysqlPlayerDataBridge in Bungeecord Server, if the player is offline and not dead in combat, all equipment items will disappear after logging in again!

Details: 
After logging in to lobby and bungee to World server, all items on the player will disappear
I had enabled NPC

Sorry for my bad english... :(

**Comment by ChanceSD** [comment]
It says this in MySQL Player Data Bridge page: https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/
![image](https://user-images.githubusercontent.com/5256215/120909929-51731500-c672-11eb-8e28-4d3eaf455452.png)
So, I guess you have to disable NPCs and only use kill on logout because they don't support it, nothing I can do.
