### ISSUE TITLE
KingdomsX-Support

### ISSUE THREAD

**Issue by Effendil** [ChanceSD/PvPManager-Issues#188]
**Is your feature request related to a problem? Please describe.**
It's some kind of Problem yeah. I really want to use the Plugin but i need support for
https://www.spigotmc.org/resources/kingdomsx.77670/
to do so ^^.

**Describe the solution you'd like**
Adding support for the plugin i mentioned above. Its a really cool and advanced factions-like plugin
with unique features i don't wanna miss on my server.

**Comment by ChanceSD** [comment]
What kind of support would be needed? Is there any specific incompatibility with that plugin?

**Comment by Effendil** [comment]
To support all the pvp-mechanics of the plugin.

Masswar dont allow to avoid pvp as example. Or that noone can flee into a claimed area of that plugin.

the typical things. And protection from pve and pvp must be stopped if a nation is in a war with another because the plugin has pve-guards that help defending the area and stuff.

Things like that ^^.

I really hope that can be done =).

excuse but my english is very bad i dont know how to say it better ^^.

**Comment by ChanceSD** [comment]
I see, at least the protection removal while in a war I believe I can add.
Will leave this open so I remember to add it later.

**Comment by Effendil** [comment]
And whats with the rest? Can you add that too? Or is that already in somehow?

Because Factions and other more common plugins have such support.

**Comment by ChanceSD** [comment]
Factions only has support for one thing, when the Vulnerable config option is enabled everyone tagged can attack everyone, even their own team.
The support I added for Factions makes it so that you can't attack your own team when Vulnerable is on.

That's all it does, alternatively you could just disable Vulnerable in the config and do the same thing. 
Is that support necessary for Kingdoms? I think you could just disable vulnerable if there's an issue.

About stopping fleeing into an area, currently only WorldGuard and Lands have support for that, and I don't plan to add support for more right now (Still need to add Griefprevention first). But might add it for Kingdoms and others after that.

So the priority for now would be disabling newbie protection and PvP protection if there's a war happening.

**Comment by ChanceSD** [comment]
I added a hook to disable protection when players are in an invasion.
I'm not sure if you're using the free version or the premium but it would be helpful if you could test it https://ci.codemc.io/job/ChanceSD/job/PvPManager/
That's the free version, it will be added into the premium in next updates
