### ISSUE TITLE
[Minor] World Height Issues With Elytra

### ISSUE THREAD

**Issue by ericlmao** [ChanceSD/PvPManager-Issues#193]
**Describe the bug**
While in combat, using an Elytra and rocketing into a claim above the world height will allow you to fly in, but the pushback feature will make players go crazy. Video below.

**To Reproduce**
While in combat, use an Elytra at the world height limit and fly over the client-side glass border

**Expected behavior**
The automatic pushback feature, as shown in the video

**Plugin and Server version**
PvPManager version 3.34.37
git-Purpur-2176 (MC: 1.20.4)*

**Video**
https://www.youtube.com/watch?v=6IKmEMSys0w

**Additional context**
As the pushback feature is working, I wouldn't classify this as a significant problem, but something to be fixed at some point if possible.

**Comment by ChanceSD** [comment]
Is the problem that the glass border doesn't show from above the region or that they can get above?
If the first one then you could switch from FAST to FULL mode and the border will probably show but don't really recommend to switch since it's a lot more inefficient than FAST.
Being able to get above the region should be normal, I assume the region only goes up to world height.

**Comment by ericlmao** [comment]
Yeah the players in the video are flying above world height and obviously the glass cannot be rendered. The problem is the push back system doesn't kick in until they land their Elytras. That's where you see them get flung around like crazy.

**Comment by ChanceSD** [comment]
I don't think this will be fixed/modified, the region probably only goes up to that block level.
